import express from 'express';

import bodyParser from 'body-parser';

import cloudinary from './db/cloudinary';

const fs = require('fs');

const fileupload = require('express-fileupload');

const app = express();

const uploads = {};

//Routes Middlewares
app.get('/', (req, res) =>
{
    // res.send('Hello user, more coming...');
    res.status(200).send({ 'message': 'YAY! Congratulations! Your first endpoint is working' });
});


app.use((req, res, next) =>
{
	res.setHeader('Access-Control-Allow-Origin', '*');
	
	res.setHeader('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content, Accept, Content-Type, Authorization');
	
	res.setHeader('Access-Control-Allow-Methods', 'GET, POST, PUT, DELETE, PATCH, OPTIONS');
	next();
});

app.use(bodyParser.json({ limit: '100mb' }));
app.use(bodyParser.urlencoded({ limit: '50mb', extended: 'true' }));
app.use(bodyParser.json({ type: 'application/vnd.api+json' }));

// upload photos

cloudinary.uploader.upload('bad.jpg', { tags: 'basic_sample' }, function (err, image) {
  console.log();
  console.log("** File Upload");
  if (err) { console.warn(err); }
  console.log("* public_id for the uploaded image is generated by Cloudinary's service.");
  console.log("* " + image.public_id);
  console.log("* " + image.url);
});

module.exports = app;