CREATE TABLE IF NOT EXIST users(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    firstname text NOT NULL CHECK (firstname <> ''),
    lastname text NOT NULL CHECK (lastname <> ''),
    email text NOT NULL CHECK (email <> ''),
    password text NOT NULL CHECK (password <> ''),
    gender text NOT NULL CHECK (gender <> ''),
    jobRole text NOT NULL CHECK (jobRole <> ''),
    department text NOT NULL CHECK (department <> ''),
    is_admin text NOT NULL CHECK (is_admin <> '')
);